from,to,weight
Rinsdorf,Sandhu,3
Sandhu,Rinsdorf,3
Sandhu,Hassenstein,3
Hassenstein,Ritz,3
Kamps,Rinsdorf,3
Kamps,Hafner,1
Sandhu,Kamps,3
Maeder,Bader,3
Bader,Maeder,3
Bader,Hafner,3
Bader,Rinsdorf,1
Maeder,Pfalzgraf,3
Ritz,Sandhu,1